class Checkout{
    constructor(){
        this.values = [
            { value: 60, label: 'Triple 20' },
            { value: 57, label: 'Triple 19' },
            { value: 54, label: 'Triple 18' },
            { value: 50, label: 'Bullseye' },
            { value: 48, label: 'Triple 16' },
            { value: 45, label: 'Triple 15' },
            { value: 43, label: 'Triple 11' },
            { value: 40, label: 'Double 20' },
            { value: 38, label: 'Double 19' },
            { value: 36, label: 'Double 18' },
            { value: 35, label: 'Double 17' },
            { value: 33, label: 'Double 16' },
            { value: 31, label: 'Double 15' },
            { value: 30, label: 'Double 15' },
            { value: 28, label: 'Double 14' },
            { value: 27, label: 'Double 13' },
            { value: 25, label: 'Double 12' },
            { value: 24, label: 'Double 12' },
            { value: 23, label: 'Double 11' },
            { value: 21, label: 'Double 10' },
            { value: 20, label: 'Double 10' },
            { value: 19, label: 'Double 9' },
            { value: 18, label: 'Double 9' },
            { value: 17, label: 'Double 8' },
            { value: 16, label: 'Double 8' },
            { value: 15, label: 'Double 7' },
            { value: 14, label: 'Double 7' },
            { value: 13, label: 'Double 6' },
            { value: 12, label: 'Double 6' },
            { value: 11, label: 'Double 5' },
            { value: 10, label: 'Double 5' },
            { value: 9, label: 'Double 4' },
            { value: 8, label: 'Double 4' },
            { value: 7, label: 'Double 3' },
            { value: 6, label: 'Double 3' },
            { value: 5, label: 'Double 2' },
            { value: 4, label: 'Double 2' },
            { value: 3, label: 'Double 1' },
            { value: 2, label: 'Double 1' },
            { value: 1, label: 'Single 1' }
        ]
    }
}